# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  tryHackMe-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set-up Git
        run: |
          git config --global user.name '${{ secrets.NAME }}'
          git config --global user.email '${{ secrets.EMAIL }}'
          git remote set-url origin https://x-access-token:${{ secrets.METRICS_TOKEN }}@github.com/${{ github.repository }}

      - name: Updating tryHackMe badge image
        run: |
          make push-thm-badge

  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generating metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: sylvain-lavazais
          template: classic
          base: header, repositories
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 100
          plugin_starlists_limit_repositories: 100
          plugin_starlists_only: Personal
          repositories_forks: yes
