# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  tryHackMe-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Cache virtualenv
        uses: actions/cache@v5.0.5
        with:
          path: ./.venv/
          key: ${{ runner.os }}-3.14-venv-${{ hashFiles('script/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-3.14-venv-${{ hashFiles('script/requirements.txt') }}

      - name: Set-up Git
        run: |
          git config --global user.name '${{ secrets.NAME }}'
          git config --global user.email '${{ secrets.EMAIL }}'
          git remote set-url origin https://x-access-token:${{ secrets.METRICS_TOKEN }}@github.com/${{ github.repository }}

      - name: Updating tryHackMe badge image
        run: |
          python --version
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r ./script/requirements.txt
          python ./script/scrap_thm_profile.py
